### ISSUE TITLE
Flashmessages (CSS/Design)

### ISSUE THREAD

**Issue by WictorKihlbaum** [johnnypesola/1dv450-jp222px#1]
Samtliga "flashmessages" är färgade gult. Det hade varit mer användarvänligt att låta dessa meddelanden vara gröna vid lyckade användarfall (Generering av ny API-nyckel, lyckad utloggning) och röda vid misslyckade användarfall (Nekad åtkomst pga att admin-rättigheter krävs). I övrigt är meddelandena mycket bra :) 

**Förslag**:
`flash[:success] = "Lyckat användarfall!"`
`flash[:danger] = "Misslyckat användarfall!"`

**Comment by johnnypesola** [comment]
Tillämpade detta förslag. "Flashmessages" vid lyckade handlingar är nu gröna och röda vid misslyckade handlingar.
