### ISSUE TITLE
Förbättring av HATEOAS

### ISSUE THREAD

**Issue by mp222sf** [johnnypesola/1dv450-jp222px#10]
Ett "Report-item" innehåller "clientuser_id" och "location_id". Hade varit bra om det finns länkar till de objekten så att det följer HATEOAS.
T.ex. "location_href" : "/api/v1/locations/1".

**Comment by johnnypesola** [comment]
Detta hade jag missat
Nu får man `location_href`med url till platsen som svar. Länk till användare finns inte i dagsläget då det inte finns en controller inbyggt i API för tillfället. Om detta behövs i klientapplikationen så byggs detta till. 

Se exempelsvar nedan för implementerad lösning.

```
{
      "id": 13,
      "route_name": "Schyssta leden",
      "route_grade": "6a",
      "clientuser_id": 1,
      "location_id": 1,
      "created_at": "2016-02-26T16:37:34.000Z",
      "updated_at": "2016-02-26T16:37:34.000Z",
      "href": "http://192.168.1.12:3000/api/v1/reports/13",
      "href_location": "http://192.168.1.12:3000/api/v1/locations/1"
    },
```
