### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by mc22ft** [johnnypesola/1dv450-jp222px#18]
Jag kan se taggar som inte tillhör någon rapport. Blir en massa taggar som inte är till någon nytta?

**Comment by mc22ft** [comment]
Hoppas jag inte var för hård. Jag tog upp dom sakerna som jag tycker var fel. Du kanske har tänkt på ett helt annat sätt. 
I överlag så tycker jag applikationen var riktigt bra gjord!!!

**Comment by johnnypesola** [comment]
Tjo, nej då. Du har inte alls varit för hård. Har inte haft tid att tag i detta förrän nu.

De taggar som finns (förutom dem som lagts till i testsyfte) är sådana begrepp som finns inom klättervärlden. Beroende vad man har klättrat för typ av klätterled så använder man olika kombinationer av dessa taggar för att kunna kategorisera sin inrapporterade klättring. Hoppas att det blev mer tydligt.

Tack förresten :+1:
