### ISSUE TITLE
Admin saknar länk till applikationsregistrering

### ISSUE THREAD

**Issue by WictorKihlbaum** [johnnypesola/1dv450-jp222px#2]
När man loggar in som admin redirect:as man till "users"-sidan _(http://www.pesola.se:3000/users)_ vilket är snyggt. Dock saknas där en länk till sidan där man som admin kan registrera applikationer. Man kan endast komma till den sidan om man "tvingar" URL:en _"http://www.pesola.se:3000/keys/key"_.  Väl där finns heller ingen länk för admin att navigera (tillbaka) till users-sidan.

**Comment by johnnypesola** [comment]
Skapade nya [menyknappar](https://github.com/johnnypesola/1dv450-jp222px/blob/master/backend/app/views/layouts/_logged_in_header.html.erb#L13-L17) specifika för när man är inloggad som admin. 

Nu så går det att navigera emellan sidorna på ett enkelt sätt när man är admin.
