### ISSUE TITLE
Redirect till login-sida vid nekad åtkomst (ej admin-rättighet)

### ISSUE THREAD

**Issue by WictorKihlbaum** [johnnypesola/1dv450-jp222px#5]
Om man "tvingar" URL:en "http://www.pesola.se:3000/users" och inte är inloggad som admin redirect:as man till login-sidan (och därmed loggas ut per automatik tolkar jag det som).  
Jag tycker att ett bättre alternativ skulle vara att redirect:a användaren till dennes egna sida med registrerade API-nycklar. Eventuellt där visa användaren ett meddelande som talar om att denne ej har de rättigheter som krävs.  

Ett förslag på hur man skulle kunna skriva "access_denied"-funktionen: 

```
def access_denied 

  if logged_in? 
   redirect_to userkeys_url 
  else 
   redirect_to login_path 
  end 

  flash[:notice] = "Access denied. Please login as Admin." 

end  
```

Om man dock Ska behålla redirect:en till login-sidan tycker jag att man ska komplettera "Access denied"-texten med en text som även förklarar att användaren försöker nå en sida vilken kräver admin-rättigheter. Därmed hänvisar man till login-formuläret som ju presenteras. Detta plus en kompletterande "Tillbaka"-knapp så att användaren kan klicka sig tillbaka till sin egen sida (I det fall användaren var inloggad sedan tidigare).

**Comment by johnnypesola** [comment]
Tack för ett bra förslag. Jag gjorde en variant och skrev om [check_admin_login](https://github.com/johnnypesola/1dv450-jp222px/blob/master/backend/app/controllers/application_controller.rb#L36-L54) metoden med inspiration ifrån ditt förslag. Det fungerar nu som önskas.
