### ISSUE TITLE
Ersätta 'user.has_role?("Admin")' med 'user.is_admin?'

### ISSUE THREAD

**Issue by WictorKihlbaum** [johnnypesola/1dv450-jp222px#6]
Du skulle kunna ersätta 'user.has_role?("Admin")' med 'user.is_admin?' på raderna #48 i 'users_controller' och #37 i 'application_controller', eftersom du redan har en definierad funktion på raderna #36-38 i 'user.rb'. På detta sätt slipper du även sträng-beroenden. I det hypotetiska fall du skulle byta namn på "Admin"-rollen.

**Comment by johnnypesola** [comment]
Detta hade jag missat. Har nu tillämpat detta. Tack för tipsen :+1:
