### ISSUE TITLE
Behövs alla egenskaper presenteras?

### ISSUE THREAD

**Issue by mp222sf** [johnnypesola/1dv450-jp222px#7]
Behövs id, created_at och updated_at i API:et?
När man hämtar Get Locations så kanske Latitude, Longitude, Name och Href räcker. Id:et behöver inte en slutanvändare veta om, så länge det följer HATEOAS och du kan klicka dig vidare till objektet.
Jag själv hade tagit bort id, created_at och updated_at, men det är upp till dig hur du vill designa ditt API.

**Comment by johnnypesola** [comment]
För min del kan `id` komma till användning i klientapplikationen som ett värde för att identifiera ett unikt objekt istället för att använda mig av endast `href` eller i värsta fall parsa ut `id` ifrån `href`. Av den anledningen väljer jag att behålla `id`.

Just `cradted_at` och `updated_at` tycker jag för stunden är intressanta fält som tillför någonting för klientapplikationen. Ifall det visar sig att jag inte har behov av dessa egenskaper så kan jag då välja att ta bort dessa.
